---
- hosts: all
  become: yes
  tasks: 
  - name: i want to install webserver
    ansible.builtin.apt:
       name: apache2
       state: present 

  - name: i want to git webserver
    ansible.builtin.apt:
       name: git
       state: present 

  - name: Start apache2 webserver, if not started
    ansible.builtin.service:
      name: apache2
      state: started